### ISSUE TITLE
Add badges for security scans to the repos

### ISSUE THREAD

**Issue by Wolftousen** [liatrio/liatrio-react-dora#89]
This needs to be done in all repos:

- https://github.com/liatrio/backstage-liatrio-dora-plugin
- https://github.com/liatrio/react-dora-charts
- https://github.com/liatrio/liatrio-dora-api

**Comment by nsshaddox** [comment]
This issue has been closed with these PRs

https://github.com/liatrio/backstage-liatrio-dora-plugin/pull/71
https://github.com/liatrio/react-dora-charts/pull/7
https://github.com/liatrio/liatrio-dora-api/pull/34
